// --- FILE SYSTEM (Auto-Generated) ---
// Generated by generate_portfolio.py
// Edit folders in 'assets/portfolio' to update this.

var fileSystem = {
    // --- STATIC DEMO CONTENT (Preserved) ---
    "Project A": {
        type: "folder",
        contents: [
            { name: "Requirements.txt", type: "file", icon: "📄" },
            { name: "Design_Mockup.png", type: "image", icon: "🖼️", src: "https://via.placeholder.com/300/000000/FFFFFF/?text=Design+Mockup" },
            { name: "Code_Snippet.js", type: "file", icon: "📜" }
        ]
    },
    
    // --- DYNAMIC CONTENT ---
    // (Generated from assets/portfolio)

    "Comissioned Works": {
        "name": "Comissioned Works",
        "type": "folder",
        "icon": "\ud83d\udcc1",
        "contents": [
            {
                "name": "QueerBeat-SunilMohan",
                "type": "folder",
                "icon": "\ud83d\udcc1",
                "contents": [
                    {
                        "name": "SR-CW-QB-001.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-001.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-001.jpg"
                    },
                    {
                        "name": "SR-CW-QB-002.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-002.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-002.jpg"
                    },
                    {
                        "name": "SR-CW-QB-003.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-003.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-003.jpg"
                    },
                    {
                        "name": "SR-CW-QB-004.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-004.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-004.jpg"
                    },
                    {
                        "name": "SR-CW-QB-005.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-005.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-005.jpg"
                    },
                    {
                        "name": "SR-CW-QB-006.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-006.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-006.jpg"
                    },
                    {
                        "name": "SR-CW-QB-007.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-007.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-007.jpg"
                    },
                    {
                        "name": "SR-CW-QB-008.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-008.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-008.jpg"
                    },
                    {
                        "name": "SR-CW-QB-009.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-009.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-009.jpg"
                    },
                    {
                        "name": "SR-CW-QB-010.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-010.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-010.jpg"
                    },
                    {
                        "name": "SR-CW-QB-011.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-011.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-011.jpg"
                    },
                    {
                        "name": "SR-CW-QB-012.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-012.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-012.jpg"
                    },
                    {
                        "name": "SR-CW-QB-013.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-013.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-013.jpg"
                    },
                    {
                        "name": "SR-CW-QB-014.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-014.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-014.jpg"
                    },
                    {
                        "name": "SR-CW-QB-015.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-015.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-015.jpg"
                    },
                    {
                        "name": "SR-CW-QB-016.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-016.jpg",
                        "thumb": "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/thumbnails/SR-CW-QB-016.jpg"
                    }
                ]
            }
        ]
    },
    "Dharavi HipHop Scene-MAIR 2024": {
        "name": "Dharavi HipHop Scene-MAIR 2024",
        "type": "folder",
        "icon": "\ud83d\udcc1",
        "contents": [
            {
                "name": "Dopeadelicz",
                "type": "folder",
                "icon": "\ud83d\udcc1",
                "contents": [
                    {
                        "name": "SR-DH-DO-001.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-001.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-001.jpg"
                    },
                    {
                        "name": "SR-DH-DO-002.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-002.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-002.jpg"
                    },
                    {
                        "name": "SR-DH-DO-003.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-003.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-003.jpg"
                    },
                    {
                        "name": "SR-DH-DO-004.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-004.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-004.jpg"
                    },
                    {
                        "name": "SR-DH-DO-005.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-005.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-005.jpg"
                    },
                    {
                        "name": "SR-DH-DO-006.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-006.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-006.jpg"
                    },
                    {
                        "name": "SR-DH-DO-007.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-007.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-007.jpg"
                    },
                    {
                        "name": "SR-DH-DO-008.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-008.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-008.jpg"
                    },
                    {
                        "name": "SR-DH-DO-009.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-009.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-009.jpg"
                    },
                    {
                        "name": "SR-DH-DO-010.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-010.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-010.jpg"
                    },
                    {
                        "name": "SR-DH-DO-011.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-011.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-011.jpg"
                    },
                    {
                        "name": "SR-DH-DO-012.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-012.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-012.jpg"
                    },
                    {
                        "name": "SR-DH-DO-013.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-013.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-013.jpg"
                    },
                    {
                        "name": "SR-DH-DO-014.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-014.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-014.jpg"
                    },
                    {
                        "name": "SR-DH-DO-015.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-015.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-015.jpg"
                    },
                    {
                        "name": "SR-DH-DO-016.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-016.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-016.jpg"
                    },
                    {
                        "name": "SR-DH-DO-017.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-017.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-017.jpg"
                    },
                    {
                        "name": "SR-DH-DO-018.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-018.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-018.jpg"
                    },
                    {
                        "name": "SR-DH-DO-019.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-019.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-019.jpg"
                    },
                    {
                        "name": "SR-DH-DO-020.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-020.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-020.jpg"
                    },
                    {
                        "name": "SR-DH-DO-021.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-021.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-021.jpg"
                    },
                    {
                        "name": "SR-DH-DO-022.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-022.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-022.jpg"
                    },
                    {
                        "name": "SR-DH-DO-023.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-023.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-023.jpg"
                    },
                    {
                        "name": "SR-DH-DO-024.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-024.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-024.jpg"
                    },
                    {
                        "name": "SR-DH-DO-025.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-025.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-025.jpg"
                    },
                    {
                        "name": "SR-DH-DO-026.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-026.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-026.jpg"
                    },
                    {
                        "name": "SR-DH-DO-027.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-027.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-027.jpg"
                    },
                    {
                        "name": "SR-DH-DO-028.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-028.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-028.jpg"
                    },
                    {
                        "name": "SR-DH-DO-029.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-029.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-029.jpg"
                    },
                    {
                        "name": "SR-DH-DO-030.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-030.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-030.jpg"
                    },
                    {
                        "name": "SR-DH-DO-031.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-031.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/thumbnails/SR-DH-DO-031.jpg"
                    }
                ]
            },
            {
                "name": "FeniFina",
                "type": "folder",
                "icon": "\ud83d\udcc1",
                "contents": [
                    {
                        "name": "SR-DH-FF-001.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-001.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/thumbnails/SR-DH-FF-001.jpg"
                    },
                    {
                        "name": "SR-DH-FF-002.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-002.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/thumbnails/SR-DH-FF-002.jpg"
                    },
                    {
                        "name": "SR-DH-FF-003.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-003.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/thumbnails/SR-DH-FF-003.jpg"
                    },
                    {
                        "name": "SR-DH-FF-004.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-004.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/thumbnails/SR-DH-FF-004.jpg"
                    },
                    {
                        "name": "SR-DH-FF-005.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-005.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/thumbnails/SR-DH-FF-005.jpg"
                    },
                    {
                        "name": "SR-DH-FF-006.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-006.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/thumbnails/SR-DH-FF-006.jpg"
                    },
                    {
                        "name": "SR-DH-FF-007.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-007.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/thumbnails/SR-DH-FF-007.jpg"
                    },
                    {
                        "name": "SR-DH-FF-008.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-008.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/thumbnails/SR-DH-FF-008.jpg"
                    },
                    {
                        "name": "SR-DH-FF-009.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-009.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/thumbnails/SR-DH-FF-009.jpg"
                    },
                    {
                        "name": "SR-DH-FF-010.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-010.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/thumbnails/SR-DH-FF-010.jpg"
                    }
                ]
            },
            {
                "name": "HipHopPathshala",
                "type": "folder",
                "icon": "\ud83d\udcc1",
                "contents": [
                    {
                        "name": "SR-DH-HH-001.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-001.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/thumbnails/SR-DH-HH-001.jpg"
                    },
                    {
                        "name": "SR-DH-HH-002.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-002.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/thumbnails/SR-DH-HH-002.jpg"
                    },
                    {
                        "name": "SR-DH-HH-003.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-003.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/thumbnails/SR-DH-HH-003.jpg"
                    },
                    {
                        "name": "SR-DH-HH-004.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-004.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/thumbnails/SR-DH-HH-004.jpg"
                    },
                    {
                        "name": "SR-DH-HH-005.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-005.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/thumbnails/SR-DH-HH-005.jpg"
                    },
                    {
                        "name": "SR-DH-HH-006.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-006.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/thumbnails/SR-DH-HH-006.jpg"
                    },
                    {
                        "name": "SR-DH-HH-007.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-007.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/thumbnails/SR-DH-HH-007.jpg"
                    },
                    {
                        "name": "SR-DH-HH-008.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-008.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/thumbnails/SR-DH-HH-008.jpg"
                    },
                    {
                        "name": "SR-DH-HH-009.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-009.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/thumbnails/SR-DH-HH-009.jpg"
                    },
                    {
                        "name": "SR-DH-HH-010.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-010.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/thumbnails/SR-DH-HH-010.jpg"
                    },
                    {
                        "name": "SR-DH-HH-011.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-011.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/thumbnails/SR-DH-HH-011.jpg"
                    },
                    {
                        "name": "SR-DH-HH-012.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-012.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/thumbnails/SR-DH-HH-012.jpg"
                    },
                    {
                        "name": "SR-DH-HH-013.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-013.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/thumbnails/SR-DH-HH-013.jpg"
                    },
                    {
                        "name": "SR-DH-HH-014.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-014.jpg",
                        "thumb": "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/thumbnails/SR-DH-HH-014.jpg"
                    }
                ]
            }
        ]
    },
    "Hyundai-ArtForHope2024": {
        "name": "Hyundai-ArtForHope2024",
        "type": "folder",
        "icon": "\ud83d\udcc1",
        "contents": [
            {
                "name": "SR-HY-001.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-001.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-001.jpg"
            },
            {
                "name": "SR-HY-002.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-002.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-002.jpg"
            },
            {
                "name": "SR-HY-003.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-003.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-003.jpg"
            },
            {
                "name": "SR-HY-004.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-004.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-004.jpg"
            },
            {
                "name": "SR-HY-005.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-005.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-005.jpg"
            },
            {
                "name": "SR-HY-006.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-006.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-006.jpg"
            },
            {
                "name": "SR-HY-007.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-007.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-007.jpg"
            },
            {
                "name": "SR-HY-008.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-008.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-008.jpg"
            },
            {
                "name": "SR-HY-009.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-009.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-009.jpg"
            },
            {
                "name": "SR-HY-010.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-010.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-010.jpg"
            },
            {
                "name": "SR-HY-011.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-011.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-011.jpg"
            },
            {
                "name": "SR-HY-012.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-012.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-012.jpg"
            },
            {
                "name": "SR-HY-013.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-013.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-013.jpg"
            },
            {
                "name": "SR-HY-014.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-014.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-014.jpg"
            },
            {
                "name": "SR-HY-015.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-015.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-015.jpg"
            },
            {
                "name": "SR-HY-016.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-016.jpg",
                "thumb": "assets/portfolio/Hyundai-ArtForHope2024/thumbnails/SR-HY-016.jpg"
            }
        ]
    },
    "Kulasai-CPB Darkroom Grant": {
        "name": "Kulasai-CPB Darkroom Grant",
        "type": "folder",
        "icon": "\ud83d\udcc1",
        "contents": [
            {
                "name": "SR-KU-001.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-001.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-001.jpg"
            },
            {
                "name": "SR-KU-002.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-002.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-002.jpg"
            },
            {
                "name": "SR-KU-003.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-003.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-003.jpg"
            },
            {
                "name": "SR-KU-004.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-004.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-004.jpg"
            },
            {
                "name": "SR-KU-005.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-005.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-005.jpg"
            },
            {
                "name": "SR-KU-006.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-006.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-006.jpg"
            },
            {
                "name": "SR-KU-007.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-007.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-007.jpg"
            },
            {
                "name": "SR-KU-008.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-008.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-008.jpg"
            },
            {
                "name": "SR-KU-009.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-009.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-009.jpg"
            },
            {
                "name": "SR-KU-010.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-010.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-010.jpg"
            },
            {
                "name": "SR-KU-011.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-011.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-011.jpg"
            },
            {
                "name": "SR-KU-012.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-012.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-012.jpg"
            },
            {
                "name": "SR-KU-013.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-013.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-013.jpg"
            },
            {
                "name": "SR-KU-014.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-014.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-014.jpg"
            },
            {
                "name": "SR-KU-015.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-015.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-015.jpg"
            },
            {
                "name": "SR-KU-016.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-016.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-016.jpg"
            },
            {
                "name": "SR-KU-017.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-017.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-017.jpg"
            },
            {
                "name": "SR-KU-018.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-018.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-018.jpg"
            },
            {
                "name": "SR-KU-019.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-019.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-019.jpg"
            },
            {
                "name": "SR-KU-020.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-020.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-020.jpg"
            },
            {
                "name": "SR-KU-021.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-021.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-021.jpg"
            },
            {
                "name": "SR-KU-022.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-022.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-022.jpg"
            },
            {
                "name": "SR-KU-023.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-023.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-023.jpg"
            },
            {
                "name": "SR-KU-024.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-024.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-024.jpg"
            },
            {
                "name": "SR-KU-025.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-025.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-025.jpg"
            },
            {
                "name": "SR-KU-026.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-026.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-026.jpg"
            },
            {
                "name": "SR-KU-027.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-027.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-027.jpg"
            },
            {
                "name": "SR-KU-028.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-028.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-028.jpg"
            },
            {
                "name": "SR-KU-029.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-029.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-029.jpg"
            },
            {
                "name": "SR-KU-030.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-030.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-030.jpg"
            },
            {
                "name": "SR-KU-031.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-031.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-031.jpg"
            },
            {
                "name": "SR-KU-032.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-032.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-032.jpg"
            },
            {
                "name": "SR-KU-033.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-033.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-033.jpg"
            },
            {
                "name": "SR-KU-034.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-034.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-034.jpg"
            },
            {
                "name": "SR-KU-035.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-035.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-035.jpg"
            },
            {
                "name": "SR-KU-036.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-036.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-036.jpg"
            },
            {
                "name": "SR-KU-037.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-037.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-037.jpg"
            },
            {
                "name": "SR-KU-038.jpg",
                "type": "image",
                "icon": "\ud83d\uddbc\ufe0f",
                "src": "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-038.jpg",
                "thumb": "assets/portfolio/Kulasai-CPB Darkroom Grant/thumbnails/SR-KU-038.jpg"
            }
        ]
    },
    "Vikatan Thadam - Cover Shoot": {
        "name": "Vikatan Thadam - Cover Shoot",
        "type": "folder",
        "icon": "\ud83d\udcc1",
        "contents": [
            {
                "name": "ChandruSir",
                "type": "folder",
                "icon": "\ud83d\udcc1",
                "contents": [
                    {
                        "name": "SR-TC-CH-001.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-001.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-001.jpg"
                    },
                    {
                        "name": "SR-TC-CH-002.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-002.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-002.jpg"
                    },
                    {
                        "name": "SR-TC-CH-003.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-003.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-003.jpg"
                    },
                    {
                        "name": "SR-TC-CH-004.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-004.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-004.jpg"
                    },
                    {
                        "name": "SR-TC-CH-005.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-005.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-005.jpg"
                    },
                    {
                        "name": "SR-TC-CH-006.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-006.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-006.jpg"
                    },
                    {
                        "name": "SR-TC-CH-007.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-007.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-007.jpg"
                    },
                    {
                        "name": "SR-TC-CH-008.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-008.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-008.jpg"
                    },
                    {
                        "name": "SR-TC-CH-009.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-009.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-009.jpg"
                    },
                    {
                        "name": "SR-TC-CH-010.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-010.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-010.jpg"
                    },
                    {
                        "name": "SR-TC-CH-011.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-011.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-011.jpg"
                    },
                    {
                        "name": "SR-TC-CH-012.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-012.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-012.jpg"
                    },
                    {
                        "name": "SR-TC-CH-013.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-013.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-013.jpg"
                    },
                    {
                        "name": "SR-TC-CH-014.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-014.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-014.jpg"
                    },
                    {
                        "name": "SR-TC-CH-015.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-015.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-015.jpg"
                    },
                    {
                        "name": "SR-TC-CH-016.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-016.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-016.jpg"
                    },
                    {
                        "name": "SR-TC-CH-017.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-017.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-017.jpg"
                    },
                    {
                        "name": "SR-TC-CH-018.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-018.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-018.jpg"
                    },
                    {
                        "name": "SR-TC-CH-019.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-019.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-019.jpg"
                    },
                    {
                        "name": "SR-TC-CH-020.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-020.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-020.jpg"
                    },
                    {
                        "name": "SR-TC-CH-021.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-021.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-021.jpg"
                    },
                    {
                        "name": "SR-TC-CH-022.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-022.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-022.jpg"
                    },
                    {
                        "name": "SR-TC-CH-023.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-023.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-023.jpg"
                    },
                    {
                        "name": "SR-TC-CH-024.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-024.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-024.jpg"
                    },
                    {
                        "name": "SR-TC-CH-025.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-025.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-025.jpg"
                    },
                    {
                        "name": "SR-TC-CH-026.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-026.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-026.jpg"
                    },
                    {
                        "name": "SR-TC-CH-027.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-027.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-027.jpg"
                    },
                    {
                        "name": "SR-TC-CH-028.jpg",
                        "type": "image",
                        "icon": "\ud83d\uddbc\ufe0f",
                        "src": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-028.jpg",
                        "thumb": "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/thumbnails/SR-TC-CH-028.jpg"
                    }
                ]
            }
        ]
    }
,
};