window.PORTFOLIO_IMAGES = {
  "images": [
    "assets/portfolio/ArmenianGenocide/SR-AG-001.jpg",
    "assets/portfolio/ArmenianGenocide/SR-AG-002.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-001.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-002.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-003.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-004.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-005.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-006.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-007.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-008.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-009.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-010.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-011.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-012.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-013.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-014.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-015.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-016.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-017.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-018.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-019.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-020.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-021.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-022.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-023.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-024.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-025.jpg",
    "assets/portfolio/Cannes 2015/SR-CA-026.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-002.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-003.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-004.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-005.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-006.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-007.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-008.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-009.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-010.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-011.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-012.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-013.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-014.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-015.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-016.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-017.1.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-017.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-018.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-019.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-020.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-021.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-022.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-023.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-024.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-025.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-026.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-027.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-028.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-029.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-030.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-031.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-032.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-033.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-034.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-035.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-036.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-037.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-038.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-039.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-040.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-041.jpg",
    "assets/portfolio/CharlieHebdo/SR-HB-042.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-001.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-002.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-003.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-004.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-005.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-006.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-007.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-008.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-009.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-010.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-011.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-012.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-013.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-014.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-015.jpg",
    "assets/portfolio/Comissioned Works/QueerBeat-SunilMohan/SR-CW-QB-016.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-001.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-002.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-003.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-004.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-005.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-006.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-007.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-008.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-009.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-010.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-011.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-012.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-013.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-014.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-015.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-016.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-017.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-018.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-019.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-020.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-021.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-022.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-023.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-024.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-025.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-026.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-027.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-028.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-029.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-030.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/Dopeadelicz/SR-DH-DO-031.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-001.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-002.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-003.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-004.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-005.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-006.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-007.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-008.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-009.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/FeniFina/SR-DH-FF-010.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-001.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-002.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-003.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-004.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-005.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-006.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-007.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-008.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-009.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-010.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-011.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-012.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-013.jpg",
    "assets/portfolio/Dharavi HipHop Scene-MAIR 2024/HipHopPathshala/SR-DH-HH-014.jpg",
    "assets/portfolio/ForSale/SR-FS-SS-001.jpg",
    "assets/portfolio/ForSale/SR-FS-SS-002.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-001.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-002.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-003.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-004.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-005.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-006.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-007.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-008.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-009.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-010.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-011.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-012.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-013.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-014.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-015.jpg",
    "assets/portfolio/Hyundai-ArtForHope2024/SR-HY-016.jpg",
    "assets/portfolio/JafflongTents/SR-AG-001.jpg",
    "assets/portfolio/JafflongTents/SR-AG-002.jpg",
    "assets/portfolio/JafflongTents/SR-AG-003.jpg",
    "assets/portfolio/JafflongTents/SR-AG-004.jpg",
    "assets/portfolio/JafflongTents/SR-AG-005.jpg",
    "assets/portfolio/JafflongTents/SR-AG-006.jpg",
    "assets/portfolio/JafflongTents/SR-AG-007.jpg",
    "assets/portfolio/JafflongTents/SR-AG-008.jpg",
    "assets/portfolio/JafflongTents/SR-AG-009.jpg",
    "assets/portfolio/JafflongTents/SR-AG-010.jpg",
    "assets/portfolio/JafflongTents/SR-AG-011.jpg",
    "assets/portfolio/JafflongTents/SR-AG-012.jpg",
    "assets/portfolio/JafflongTents/SR-AG-013.jpg",
    "assets/portfolio/JafflongTents/SR-AG-014.jpg",
    "assets/portfolio/JafflongTents/SR-AG-015.jpg",
    "assets/portfolio/JafflongTents/SR-AG-016.jpg",
    "assets/portfolio/JafflongTents/SR-AG-017.jpg",
    "assets/portfolio/JafflongTents/SR-AG-018.jpg",
    "assets/portfolio/JafflongTents/SR-AG-019.jpg",
    "assets/portfolio/JafflongTents/SR-AG-020.jpg",
    "assets/portfolio/JafflongTents/SR-AG-021.jpg",
    "assets/portfolio/JafflongTents/SR-AG-022.jpg",
    "assets/portfolio/JafflongTents/SR-AG-023.jpg",
    "assets/portfolio/JafflongTents/SR-AG-024.jpg",
    "assets/portfolio/JafflongTents/SR-AG-025.jpg",
    "assets/portfolio/JafflongTents/SR-AG-026.jpg",
    "assets/portfolio/JafflongTents/SR-AG-027.jpg",
    "assets/portfolio/JafflongTents/SR-AG-028.jpg",
    "assets/portfolio/JafflongTents/SR-AG-029.jpg",
    "assets/portfolio/JafflongTents/SR-AG-030.jpg",
    "assets/portfolio/JafflongTents/SR-AG-031.jpg",
    "assets/portfolio/JafflongTents/SR-AG-032.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-001.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-002.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-003.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-004.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-005.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-006.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-007.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-008.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-009.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-010.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-011.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-012.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-013.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-014.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-015.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-016.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-017.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-018.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-019.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-020.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-021.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-022.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-023.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-024.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-025.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-026.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-027.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-028.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-029.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-030.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-031.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-032.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-033.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-034.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-035.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-036.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-037.jpg",
    "assets/portfolio/Kulasai-CPB Darkroom Grant/SR-KU-038.jpg",
    "assets/portfolio/PortraitOfLivingDead/SR-AG-001.jpg",
    "assets/portfolio/PortraitOfLivingDead/SR-AG-002.jpg",
    "assets/portfolio/PortraitOfLivingDead/SR-AG-003.jpg",
    "assets/portfolio/PortraitOfLivingDead/SR-AG-004.jpg",
    "assets/portfolio/PortraitOfLivingDead/SR-AG-005.jpg",
    "assets/portfolio/PortraitOfLivingDead/SR-AG-006.jpg",
    "assets/portfolio/PortraitOfLivingDead/SR-AG-007.jpg",
    "assets/portfolio/PortraitOfLivingDead/SR-AG-008.jpg",
    "assets/portfolio/PortraitOfLivingDead/SR-AG-009.jpg",
    "assets/portfolio/PortraitOfLivingDead/SR-AG-010.jpg",
    "assets/portfolio/PortraitOfLivingDead/SR-AG-011.jpg",
    "assets/portfolio/PortraitOfLivingDead/SR-AG-012.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/A.Marx/SR-TC-AM-001.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/A.Marx/SR-TC-AM-002.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/A.Marx/SR-TC-AM-003.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/A.Marx/SR-TC-AM-004.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/A.Marx/SR-TC-AM-005.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/A.Marx/SR-TC-AM-006.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/A.Marx/SR-TC-AM-007.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/A.Marx/SR-TC-AM-008.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/A.Marx/SR-TC-AM-009.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/A.Marx/SR-TC-AM-010.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/A.Marx/SR-TC-AM-011.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/A.Marx/SR-TC-AM-012.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/A.Marx/SR-TC-AM-013.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/A.Marx/SR-TC-AM-014.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/A.Marx/SR-TC-AM-015.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-001.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-002.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-003.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-004.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-005.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-006.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-007.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-008.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-009.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-010.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-011.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-012.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-013.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-014.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-015.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-016.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-017.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-018.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-019.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-020.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-021.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-022.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-023.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-024.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-025.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-026.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-027.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/ChandruSir/SR-TC-CH-028.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/PerumalMurugan/SR-TC-PM-001.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/PerumalMurugan/SR-TC-PM-002.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/PerumalMurugan/SR-TC-PM-003.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/PerumalMurugan/SR-TC-PM-004.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/PerumalMurugan/SR-TC-PM-005.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/PerumalMurugan/SR-TC-PM-006.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/PerumalMurugan/SR-TC-PM-007.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/PerumalMurugan/SR-TC-PM-008.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/PerumalMurugan/SR-TC-PM-009.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/PerumalMurugan/SR-TC-PM-010.jpg",
    "assets/portfolio/Vikatan Thadam - Cover Shoot/PerumalMurugan/SR-TC-PM-011.jpg"
  ]
};